version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: finance-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: finance-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  users-budgets-service:
    build: .
    container_name: users-budgets-service
    depends_on:
      - postgres
      - mongo
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    command: ["java", "-jar", "/app.jar"]

volumes:
  postgres_data:
  mongo_data:
